import 'funuicss/css/fun.css'
import 'styles/globals.css'
import Head from 'next/head'
import { useEffect } from 'react'
import DarkMode from 'funuicss/component/DarkMode'
export default function App({ Component, pageProps }) {
  useEffect(() => {
  
    var root = document.querySelector(':root');
    root.style.setProperty('--primaryColor', "#7A316F"); 
    
  })
// useEffect(() => {
//     if(localStorage.getItem("theme") == "light" && localStorage.getItem("theme")){
//         DarkMode(false)
//     }else{
//         DarkMode(true)
//     }
// }, [])
                
  return (
<>
<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </Head> 
  <div>
  <Component {...pageProps} />
  </div>
</>
  )
}

