import 'funuicss/css/fun.css'
import 'styles/globals.css'
import Head from 'next/head'
export default function App({ Component, pageProps }) {
  return (
<>
<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </Head> 
  <Component {...pageProps} />
</>
  )
}

